services:
  db:
    image: mariadb:10.6.4-focal
    expose:
      - 3306
      - 33060
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - wp_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    restart: always
volumes:
  db_data:
  wp_data:
